# Generated by Django 4.1.7 on 2023-03-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='default/avatar.png', upload_to='images/recipe/'),
        ),
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, default='default/easychef.png', upload_to='images/steps/'),
        ),
    ]
