# Generated by Django 4.1.7 on 2023-03-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0002_alter_recipe_image_alter_step_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='default/easychef.png', upload_to='images/recipe/'),
        ),
    ]
